/*-------------------------------------------------------------------------
 *
 * pg_tablegroup_d.h
 *    Macro definitions for pg_tablegroup
 *
 * Portions Copyright (c) 1996-2018, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_TABLEGROUP_D_H
#define PG_TABLEGROUP_D_H

#define TableGroupRelationId 8000
#define TablegroupRelation_Rowtype_Id 8002

#define Anum_pg_tablegroup_grpname 1
#define Anum_pg_tablegroup_grpowner 2
#define Anum_pg_tablegroup_grpacl 3
#define Anum_pg_tablegroup_grpoptions 4

#define Natts_pg_tablegroup 4


#endif							/* PG_TABLEGROUP_D_H */
